#
# File:    handc/cfg/gc/freelist/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: 1.2
# Date:    %G% 11:19:03
# Build:   v0.7.3.4-b7u, 2007-05-30
#
#


CFILES=gcserver.c
PRODUCT=xgc.o

include ../postambl.mak
