#/********************* Makefile for Module `mathlib' *********************/
#
# constructed by rsc for RScheme (v0.7.3.4-b7u, 2007-05-30),
# module `mathlib'
#
CFILES= mathlib_l.c random.c arith1.c
INCFILES=mathlib.h
PRODUCT=mathlib.o

include ../postambl.mak
