#
# File:    handc/heapi/Makefile
#
#          Copyright (C)1997 Donovan Kolbly <d.kolbly@rosette.com>
#          as part of the RScheme project, licensed for free use
#
# Version: 1.5
# Date:    %G% 10:47:21
# Build:   v0.7.3.4-b7u, 2007-05-30
#

CFILES=loadimag.c savewrit.c savetrav.c saveq.c mapf.c
PRODUCT=heapi.o

include ../postambl.mak
