
(define-generic-function KeyPress)
(define-generic-function KeyRelease)
(define-generic-function ButtonPress)
(define-generic-function ButtonRelease)
(define-generic-function MotionNotify)
(define-generic-function EnterNotify)
(define-generic-function LeaveNotify)
(define-generic-function FocusIn)
(define-generic-function FocusOut)
(define-generic-function KeymapNotify)
(define-generic-function Expose)
(define-generic-function GraphicsExpose)
(define-generic-function NoExpose)
(define-generic-function VisibilityNotify)
(define-generic-function CreateNotify)
(define-generic-function DestroyNotify)
(define-generic-function UnmapNotify)
(define-generic-function MapNotify)
(define-generic-function MapRequest)
(define-generic-function ReparentNotify)
(define-generic-function ConfigureNotify)
(define-generic-function ConfigureRequest)
(define-generic-function GravityNotify)
(define-generic-function ResizeRequest)
(define-generic-function CirculateNotify)
(define-generic-function CirculateRequest)
(define-generic-function PropertyNotify)
(define-generic-function SelectionClear)
(define-generic-function SelectionRequest)
(define-generic-function SelectionNotify)
(define-generic-function ColormapNotify)
(define-generic-function ClientMessage)
(define-generic-function MappingNotify)

(define $event-codes 
  (vector #f #f KeyPress KeyRelease ButtonPress ButtonRelease MotionNotify EnterNotify LeaveNotify FocusIn FocusOut KeymapNotify Expose GraphicsExpose NoExpose VisibilityNotify CreateNotify DestroyNotify UnmapNotify MapNotify MapRequest ReparentNotify ConfigureNotify ConfigureRequest GravityNotify ResizeRequest CirculateNotify CirculateRequest PropertyNotify SelectionClear SelectionRequest SelectionNotify ColormapNotify ClientMessage MappingNotify #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f))


(define-method KeyPress ((self <object>) event))
(define-method KeyRelease ((self <object>) event))
(define-method ButtonPress ((self <object>) event))
(define-method ButtonRelease ((self <object>) event))
(define-method MotionNotify ((self <object>) event))
(define-method EnterNotify ((self <object>) event))
(define-method LeaveNotify ((self <object>) event))
(define-method FocusIn ((self <object>) event))
(define-method FocusOut ((self <object>) event))
(define-method KeymapNotify ((self <object>) event))
(define-method Expose ((self <object>) event))
(define-method GraphicsExpose ((self <object>) event))
(define-method NoExpose ((self <object>) event))
(define-method VisibilityNotify ((self <object>) event))
(define-method CreateNotify ((self <object>) event))
(define-method DestroyNotify ((self <object>) event))
(define-method UnmapNotify ((self <object>) event))
(define-method MapNotify ((self <object>) event))
(define-method MapRequest ((self <object>) event))
(define-method ReparentNotify ((self <object>) event))
(define-method ConfigureNotify ((self <object>) event))
(define-method ConfigureRequest ((self <object>) event))
(define-method GravityNotify ((self <object>) event))
(define-method ResizeRequest ((self <object>) event))
(define-method CirculateNotify ((self <object>) event))
(define-method CirculateRequest ((self <object>) event))
(define-method PropertyNotify ((self <object>) event))
(define-method SelectionClear ((self <object>) event))
(define-method SelectionRequest ((self <object>) event))
(define-method SelectionNotify ((self <object>) event))
(define-method ColormapNotify ((self <object>) event))
(define-method ClientMessage ((self <object>) event))
(define-method MappingNotify ((self <object>) event))
