#/******************** Makefile for Module `low_scheme' ********************/
#
# constructed by rsc for RScheme (v0.7.3.4-b7u, 2007-05-30),
# module `low-scheme'
#
CFILES= low_scheme_l.c callwval.c vectops.c chars.c finding.c mapping.c append.c vectors.c lists.c
INCFILES=low_scheme.h
PRODUCT=low_scheme.o

include ../postambl.mak
