(redefine sys:+ +)
(redefine sys:- -)
(redefine sys:/ /)
(redefine sys:* *)
(redefine sys:acos acos)
(redefine sys:asin asin)
(redefine sys:atan atan)
(redefine sys:sin sin)
(redefine sys:cos cos)
(redefine sys:tan tan)
(redefine sys:sqrt sqrt)
(redefine sys:expt expt)
(redefine sys:log log)
(redefine sys:exp exp)
(redefine sys:round round)
(redefine sys:truncate truncate)
(redefine sys:floor floor)
(redefine sys:ceiling ceiling)
(redefine sys:quotient quotient)
(redefine sys:modulo modulo)
(redefine sys:remainder remainder)

;(redefine sys:<rect-complex> <rect-complex>)
;(define-generic-function complex?)
;(define-generic-function real?)
;(define-generic-function rational?)
;(define-generic-function integer?)

(define-mm-generic-function binary+)
(define-mm-generic-function binary-)
(define-mm-generic-function binary*)
(define-mm-generic-function binary/)

(define-mm-generic-function quotient)
(define-mm-generic-function remainder)
(define-mm-generic-function modulo)

;(define-generic-function numerator)
;(define-generic-function denominator)
(define-generic-function floor)
(define-generic-function ceiling)
(define-generic-function truncate)
(define-generic-function round)

(define-generic-function exp)
(define-generic-function log)
(define-generic-function sin)
(define-generic-function cos)
(define-generic-function tan)
(define-generic-function asin)
(define-generic-function acos)
(define-mm-generic-function atan)

(define-generic-function sqrt)
(define-mm-generic-function expt)

;(define-generic-function real-part)
;(define-generic-function imag-part)
(define-generic-function magnitude)
(define-generic-function angle)

