#/********************** Makefile for Module `regex' **********************/
#
# constructed by rsc for RScheme (v0.7.3.4-b7u, 2007-05-30),
# module `regex'
#
CFILES= regex_l.c rxinterp.c runmatch.c
INCFILES=regex.h
PRODUCT=regex.o

include ../postambl.mak
