#/*********************** Makefile for Module `sort' ***********************/
#
# constructed by rsc for RScheme (v0.7.3.4-b7u, 2007-05-30),
# module `sort'
#
CFILES= sort_l.c sort1.c
INCFILES=sort.h
PRODUCT=sort.o

include ../postambl.mak
