#
# File:    handc/loadboot/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: 1.1
# Date:    %G% 00:56:19
# Build:   v0.7.3.4-b7u, 2007-05-30
#

CFILES=loadboot.c
PRODUCT=ldboot.o
include ../postambl.mak
