
(define (t)
  (let-syntax ((bar (syntax-rules ()
                    ((_ v e)
                     (let-syntax ((foo (syntax-rules ()
                                         ((_ x)
                                          (+ x e)))))
                       (let ((v 1))
                         (foo e)))))))
  (let ((j 2))
    (bar j (* j 10)))))

(define (t2)
  (let-syntax ((sum (syntax-rules ()
		     ((_ j y e ...)
		      (list (let ((j y))
			      (+ j e ...))
			    (+ j e ...))))))
    (let ((k 3)
	  (j 1))
      (sum k 2
	   (* j 10)
	   (* k 100)
	   (* j 1000)
	   (* j 10000)))))
