#
# File:    handc/cfg/gc/irc/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: 1.3
# Date:    %G% 11:19:01
# Build:   v0.7.3.4-b7u, 2007-05-30
#
#


CFILES=makeheap.c gcalloc.c writebar.c ptrlist.c traverse.c
PRODUCT=xgc.o

include ../postambl.mak
