
(def (rr->bs r)
  (let* ((rdata/bs (rdata->bs (type r) (rdata r)))
	 (rdlength (len rdata/bs)))
    (bs-append (dn->bs                 (name r))
	       (uint16->bs (type->num  (type r)))
	       (uint16->bs (class->num (class r)))
	       (uint32->bs             (ttl r))
	       (uint16->bs             rdlength)
	                               rdata/bs)))

(def (rdata->bs type rdata)
  (case type
    ((CNAME)
     (dn->bs rdata))
    ((HINFO)
     (bs-append (char-string->bs (cpu rdata))
		(char-string->bs (os  rdata))))
    ((MX)
     (bs-append (uint16->bs (preference rdata))
		(dn->bs     (exchange   rdata))))
    ((NS)
     (dn->bs rdata))
    ((PTR)
     (dn->bs rdata))
    ((SOA)
     (bs-append (dn->bs     (mname   rdata))
		(dn->bs     (rname   rdata))
		(uint32->bs (serial  rdata))
		(uint32->bs (refresh rdata))
		(uint32->bs (retry   rdata))
		(uint32->bs (expire  rdata))
		(uint32->bs (minimum rdata))))
    ((A)
     (ip->bs rdata))
    ((TXT)
     (char-string->bs rdata))
    (else
     (error "rdata->bs: Can't handle type: ~s" type))))

