#/********************** Makefile for Module `objsys' **********************/
#
# constructed by rsc for RScheme (v0.7.3.4-b7u, 2007-05-30),
# module `objsys'
#
CFILES= objsys_l.c getnset.c makeinst.c genericf.c
INCFILES=objsys.h
PRODUCT=objsys.o

include ../postambl.mak
