#
# File:    handc/cfg/rdln/std/Makefile
#
#          Copyright (C)1995 Donovan Kolbly <donovan@tkg.com>
#          as part of the RScheme project, licensed for free use
#
# Version: 1.2
# Date:    %G% 11:18:57
# Build:   v0.7.3.4-b7u, 2007-05-30
#
#

CFILES=rdln_std.c
PRODUCT=rdln.o
include ../postambl.mak
