#/********************** Makefile for Module `tables' **********************/
#
# constructed by rsc for RScheme (v0.7.3.4-b7u, 2007-05-30),
# module `tables'
#
CFILES= tables_l.c make.c
INCFILES=tables.h
PRODUCT=tables.o

include ../postambl.mak
